Repository kiwiproject/embedded-eureka, pull requests merged in 2021-01, with the labels that each got.

#33 Run a real Eureka server embedded
  pom.xml
  src/main/java/org/kiwiproject/eureka/EmbeddedEurekaBootstrap.java
  src/main/java/org/kiwiproject/eureka/EmbeddedEurekaServer.java
  src/main/java/org/kiwiproject/eureka/EurekaServer.java
  src/main/java/org/kiwiproject/eureka/EurekaServletHandler.java
  src/main/java/org/kiwiproject/eureka/EurekaTestHelpers.java
  src/main/java/org/kiwiproject/eureka/RequestHandler.java
  src/main/java/org/kiwiproject/eureka/junit/EurekaServerExtension.java
  src/main/resources/eureka-client.properties
  src/main/resources/eureka-server.properties
  src/main/resources/webapp/WEB-INF/web.xml
  src/test/java/org/kiwiproject/eureka/EmbeddedEurekaBootstrapTest.java
  src/test/java/org/kiwiproject/eureka/EmbeddedEurekaServerTest.java
  src/test/java/org/kiwiproject/eureka/EurekaServerTest.java
  src/test/java/org/kiwiproject/eureka/EurekaServletHandlerTest.java
  src/test/java/org/kiwiproject/eureka/junit/EurekaServerExtensionTest.java
Labels: enhancement

#35 Suppress Resources.getResource "unstable API" warning
  src/main/java/org/kiwiproject/eureka/EmbeddedEurekaServer.java
Labels: code cleanup

#36 Update to Jackson 2.10.5
  pom.xml
Labels: dependencies

#37 Remove Powermock version property from the POM (not used)
  pom.xml
Labels: code cleanup

#38 Remove obsolete information from README
  README.md
Labels: documentation

#39 Update kiwi and kiwi-test versions
  pom.xml
Labels: dependencies

#43 Delete obsolete TravisCI config file
  .travis.yml.deleteme
Labels: code cleanup

#42 Fix example in README
  README.md
Labels: documentation
